

import java.io.FileWriter;
import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;
import org.batiz.calculoarea.Circulo;
import org.batiz.calculoarea.Rectangulo;
import org.batiz.calculoarea.Triangulo;


public class Jframe extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Jframe.class.getName());

    public Jframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoFiguras = new javax.swing.ButtonGroup();
        panelRadioButtons = new javax.swing.JPanel();
        opcionRectangulo = new javax.swing.JRadioButton();
        opcionTriangulo = new javax.swing.JRadioButton();
        opcionCirculo = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonCalcularArea = new javax.swing.JButton();
        botonGuardarResultado = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cajaBase = new javax.swing.JTextField();
        cajaAltura = new javax.swing.JTextField();
        cajaRadio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cajaArea = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        grupoFiguras.add(opcionRectangulo);
        opcionRectangulo.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        opcionRectangulo.setText("Rectángulo");

        grupoFiguras.add(opcionTriangulo);
        opcionTriangulo.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        opcionTriangulo.setText("Triángulo");
        opcionTriangulo.addActionListener(this::opcionTrianguloActionPerformed);

        grupoFiguras.add(opcionCirculo);
        opcionCirculo.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        opcionCirculo.setText("Círculo");

        javax.swing.GroupLayout panelRadioButtonsLayout = new javax.swing.GroupLayout(panelRadioButtons);
        panelRadioButtons.setLayout(panelRadioButtonsLayout);
        panelRadioButtonsLayout.setHorizontalGroup(
            panelRadioButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRadioButtonsLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelRadioButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(opcionRectangulo)
                    .addComponent(opcionCirculo)
                    .addComponent(opcionTriangulo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRadioButtonsLayout.setVerticalGroup(
            panelRadioButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRadioButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(opcionRectangulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionTriangulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionCirculo)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(190, 230, 240));

        jLabel1.setFont(new java.awt.Font("Monocraft", 1, 36)); // NOI18N
        jLabel1.setText("Cálculo de áreas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(40, 40, 40))
        );

        botonCalcularArea.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        botonCalcularArea.setText("Calcular área");
        botonCalcularArea.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 255), 2, true));
        botonCalcularArea.addActionListener(this::botonCalcularAreaActionPerformed);

        botonGuardarResultado.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        botonGuardarResultado.setText("Guardar resultado");
        botonGuardarResultado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 255), 2, true));
        botonGuardarResultado.addActionListener(this::botonGuardarResultadoActionPerformed);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        cajaBase.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cajaAltura.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cajaRadio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Base");

        jLabel3.setText("Altura");

        jLabel4.setText("Radio");

        jLabel5.setText("Área");

        cajaArea.setEditable(false);
        cajaArea.setBackground(new java.awt.Color(255, 255, 255));
        cajaArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cajaArea.addActionListener(this::cajaAreaActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cajaRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cajaBase, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cajaAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(cajaArea, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cajaBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cajaAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cajaArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cajaRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(panelRadioButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonCalcularArea, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonGuardarResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(panelRadioButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(botonCalcularArea, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonGuardarResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcionTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionTrianguloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcionTrianguloActionPerformed

    private void botonCalcularAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcularAreaActionPerformed
        if (opcionRectangulo.isSelected()) {
            if (cajaBase.getText().equals("") || cajaAltura.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Llene las cajas de texto", "Error", 2);
            } else {
                try {
                    double base = Double.parseDouble(cajaBase.getText());
                    double altura = Double.parseDouble(cajaAltura.getText());

                    Rectangulo figura = new Rectangulo();
                    cajaArea.setText(String.valueOf(figura.area(base, altura)));

                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(rootPane, "Llene las cajas de texto", "Error", 2);
                }

            }
        }
        if (opcionTriangulo.isSelected()) {
            if (cajaBase.getText().equals("") || cajaAltura.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Llene las cajas de texto", "Error", 2);
            } else {
                try {
                    double base = Double.parseDouble(cajaBase.getText());
                    double altura = Double.parseDouble(cajaAltura.getText());

                    Triangulo figura = new Triangulo();
                    cajaArea.setText(String.valueOf(figura.area(base, altura)));

                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(rootPane, "Llene las cajas de texto", "Error", 2);
                }

            }
        }
        if (opcionCirculo.isSelected()) {
            if (cajaRadio.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Llene las cajas de texto", "Error", 2);
            } else {
                try {
                    double radio = Double.parseDouble(cajaRadio.getText());
                    Circulo figura = new Circulo();
                    cajaArea.setText(String.valueOf(figura.area(radio)));

                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(rootPane, "Llene las cajas de texto", "Error", 2);
                }

            }
        }
    }//GEN-LAST:event_botonCalcularAreaActionPerformed

    private void cajaAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaAreaActionPerformed

    private void botonGuardarResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarResultadoActionPerformed
    File area = new File("area.txt");
        try {
            if (area.createNewFile()) {
                FileWriter escritor = new FileWriter(area);
                escritor.write("Area de la figura");
                escritor.write(cajaArea.getText());
                escritor.close();
                System.out.println("Archivo creado con exito");
            } else {

                FileWriter escritor = new FileWriter(area);
                escritor.write("Area de la figura: ");
                escritor.write(cajaArea.getText());
                escritor.close();
                System.out.println("Archivo sobreescrito con exito");
            }
        } catch (IOException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_botonGuardarResultadoActionPerformed


    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new Jframe().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCalcularArea;
    private javax.swing.JButton botonGuardarResultado;
    private javax.swing.JTextField cajaAltura;
    private javax.swing.JTextField cajaArea;
    private javax.swing.JTextField cajaBase;
    private javax.swing.JTextField cajaRadio;
    private javax.swing.ButtonGroup grupoFiguras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton opcionCirculo;
    private javax.swing.JRadioButton opcionRectangulo;
    private javax.swing.JRadioButton opcionTriangulo;
    private javax.swing.JPanel panelRadioButtons;
    // End of variables declaration//GEN-END:variables
}
